=== stephenwilliams/go-clitools/_build/tool.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/stephenwilliams/go-clitools/main/_build/tool.schema.json",
  "title": "CLI Tool specification schema",
  "description": "Used to generate CLI tool libraries",
  "definitions": {
    "tool": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string",
          "format": "uri"
        },
        "name": {
          "type": "string",
          "description": "Name of the CLI tool"
        },
        "description": {
          "type": "string",
          "description": "Description of the CLI tool"
        },
        "executableName": {
          "type": "string",
          "description": "Name of the executable"
        },
        "exportedName": {
          "type": "string",
          "description": "The exported name of the tool. Used for naming the tool info"
        },
        "package": {
          "type": "string",
          "pattern": "^([A-z0-9]*)$"
        },
        "groups": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commandGroup"
          },
          "uniqueItems": true,
          "minItems": 1
        },
        "optionSets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/optionSet"
          },
          "uniqueItems": true
        },
        "downloaders": {
          "$ref": "#/definitions/downloaders"
        },
        "defaultToolProvider": {
          "$ref": "#/definitions/toolProvider"
        },
        "versionProvider": {
          "$ref": "#/definitions/versionProvider"
        }
      },
      "required": [
        "name",
        "description",
        "executableName",
        "exportedName",
        "package",
        "groups",
        "versionProvider"
      ]
    },
    "stringReplacer": {
      "type": "object",
      "properties": {
        "old": {
          "type": "string"
        },
        "new": {
          "type": "string"
        },
        "numberOfReplacements": {
          "type": "integer"
        }
      },
      "required": [
        "old",
        "new"
      ]
    },
    "versionSelector": {
      "type": "object",
      "properties": {
        "splitLine": {
          "type": "object",
          "properties": {
            "index": {
              "type": "integer"
            }
          },
          "required": ["index"]
        },
        "splitString": {
          "type": "object",
          "properties": {
            "index": {
              "type": "integer"
            },
            "separator": {
              "type": "string",
              "default": " "
            }
          },
          "required": ["index"]
        },
        "stringReplace": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/stringReplacer"
          }
        },
        "trimPrefix": {
          "type": "string"
        },
        "trimSuffix": {
          "type": "string"
        },
        "equalsReplace": {
          "$ref": "#/definitions/stringReplacer"
        }
      }
    },
    "versionProvider": {
      "type": "object",
      "properties": {
        "commandArgs": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        },
        "captureStderr": {
          "type": "boolean",
          "default": false
        },
        "selector": {
          "$ref": "#/definitions/versionSelector"
        }
      },
      "required": [
        "commandArgs",
        "selector"
      ]
    },
    "goType": {
      "enum": [
        "boolean",
        "duration",
        "int",
        "string",
        "stringSlice"
      ]
    },
    "option": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "exportedName": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/goType"
        },
        "format": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        },
        "valueJoin": {
          "type": "string",
          "description": "When using type '[]string' and this is set, it changes the value injected to be string joined on this character"
        },
        "required": {
          "type": "boolean"
        },
        "noValue": {
          "type": "boolean"
        },
        "repeated": {
          "type": "boolean",
          "description": "Only valid for slice types. Whether or not the format is repeated for each value of the slice."
        },
        "append": {
          "type": "boolean",
          "description": "Only valid for slice types. Appends the values to the args array."
        }
      },
      "required": [
        "name",
        "exportedName",
        "type",
        "format"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "pattern": ".*Slice"
              }
            }
          },
          "then": {
            "oneOf": [
              {
                "required": ["valueJoin"]
              },
              {
                "required": ["repeated"]
              },
              {
                "required": ["append"]
              }
            ]
          }
        }
      ]
    },
    "argumentSet": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "exportedNameSuffix": {
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/argument"
          },
          "uniqueItems": true
        }
      },
      "required": [
        "exportedNameSuffix",
        "args"
      ]
    },
    "argument": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/goType"
        },
        "format": {
          "type": "string"
        },
        "excludeDefaultValue": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "command": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "exportedName": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "subCommandPath": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        },
        "options": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/option"
          },
          "uniqueItems": true
        },
        "optionSets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/optionSetRef"
          }
        },
        "argumentSets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/argumentSet"
          },
          "uniqueItems": true
        },
        "argsFirst": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "exportedName"
      ]
    },
    "commandGroup": {
      "type": "object",
      "properties": {
        "package": {
          "type": "string",
          "pattern": "^(@|[A-z0-9]*)$"
        },
        "description": {
          "type": "string"
        },
        "commands": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/command"
          },
          "uniqueItems": true
        },
        "groups": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commandGroup"
          },
          "uniqueItems": true
        }
      },
      "required": [
        "package",
        "description",
        "commands"
      ]
    },
    "optionSet": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "options": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/option"
          },
          "minItems": 1
        }
      },
      "required": [
        "name",
        "options"
      ]
    },
    "optionSetRef": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": ["name"]
    },
    "downloaders": {
      "type": "object",
      "properties": {
        "githubRelease": {
          "$ref": "#/definitions/githubReleaseDownloader"
        }
      }
    },
    "githubReleaseDownloader": {
      "type": "object",
      "properties": {
        "owner": {
          "type": "string",
          "description": "GitHub repository owner"
        },
        "repository": {
          "type": "string",
          "description": "GitHub repository name"
        },
        "tagPrefix": {
          "type": "string"
        },
        "assetSelector": {
          "type": "string"
        },
        "assetSelectorRegexp": {
          "type": "boolean"
        },
        "archived": {
          "type": "boolean"
        },
        "archivePath": {
          "type": "string"
        },
        "multipleReleases": {
          "type": "boolean",
          "description": "When multiple different \"releases\" are released from a singular GitHub repository"
        },
        "multipleReleasesTagPrefix": {
          "type": "string",
          "description": "When multiple different \"releases\" are released from a singular GitHub repository."
        }
      },
      "required": [
        "owner",
        "repository",
        "assetSelector"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "archived": {
                "const": true
              }
            }
          },
          "then": {
            "properties": {
              "archivePath": {
                "pattern": ".+"
              }
            },
            "required": [
              "archivePath"
            ]
          }
        }
      ]
    },
    "toolProvider": {
      "type": "object",
      "properties": {
        "chain": {
          "type": "object",
          "properties": {
            "providers": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/toolProvider"
              },
              "minItems": 2
            }
          }
        },
        "definedToolPath": {
          "type": "object",
          "properties": {
            "path": {
              "type": "string"
            }
          },
          "required": [
            "path"
          ]
        },
        "downloader": {
          "type": "object",
          "properties": {
            "downloader": {
              "type": "string"
            }
          },
          "required": ["downloader"]
        },
        "path": {
          "type": "boolean"
        }
      },
      "oneOf": [
        {
          "required": ["chain"]
        },
        {
          "required": ["definedToolPath"]
        },
        {
          "required": ["downloader"]
        },
        {
          "required": ["path"]
        }
      ]
    }
  },
  "$ref": "#/definitions/tool"
}

=== stephenwilliams/go-clitools/_build/specifications/lefthook.json
{
  "$schema": "https://raw.githubusercontent.com/stephenwilliams/go-clitools/master/tools.schema.json",
  "name": "Lefthook",
  "description": "Fast and powerful Git hooks manager for Node.js, Ruby or any other type of projects.",
  "executableName": "lefthook",
  "package": "lefthook",
  "exportedName": "Lefthook",
  "versionProvider": {
    "commandArgs": ["version"],
    "selector": {}
  },
  "groups": [
    {
      "package": "@",
      "description": "",
      "commands": [
        {
          "name": "add",
          "description": "This command will try to build the following structure in repository:\n\n├───.git\n│   └───hooks\n│       └───pre-commit // this executable will be added. Existed file with\n│                      // same name will be renamed to pre-commit.old\n(lefthook add this dirs if you run command with -d option)\n│\n├───.lefthook            // directory for project level hooks\n│   └───pre-commit     // directory with hooks executables\n├───.lefthook-local      // directory for personal hooks add it in .gitignore\n│   └───pre-commit",
          "exportedName": "Add",
          "subCommandPath": ["add"],
          "argumentSets": [
            {
              "name": "@",
              "exportedNameSuffix": "",
              "args": [
                {
                  "name": "hooksGroup",
                  "type": "string"
                }
              ]
            }
          ]
        },
        {
          "name": "install",
          "description": "Write basic configuration file in your project repository. Or initialize existed config",
          "exportedName": "Install",
          "subCommandPath": ["install"],
          "optionSets": [
            {
              "name": "base"
            }
          ]
        },
        {
          "name": "run",
          "description": "Execute group of hooks",
          "exportedName": "Run",
          "subCommandPath": ["run"],
          "argumentSets": [
            {
              "name": "@",
              "exportedNameSuffix": "",
              "args": [
                {
                  "name": "hooksGroup",
                  "type": "string"
                }
              ]
            }
          ]
        },
        {
          "name": "uninstall",
          "description": "Revert install command",
          "exportedName": "Uninstall",
          "subCommandPath": ["uninstall"],
          "options": [
            {
              "name": "keepConfig",
              "exportedName": "KeepConfig",
              "type": "boolean",
              "description": "keep configuration files and source directories present",
              "noValue": true,
              "format": ["--keep-config"]
            }
          ],
          "optionSets": [
            {
              "name": "base"
            }
          ]
        },
        {
          "name": "version",
          "description": "Show lefthook version",
          "exportedName": "Version",
          "subCommandPath": ["version"]
        }
      ]
    }
  ],
  "optionSets": [
    {
      "name": "base",
      "options": [
        {
          "name": "aggressive",
          "exportedName": "Aggressive",
          "type": "boolean",
          "description": "remove all hooks from .git/hooks dir and install lefthook hooks",
          "noValue": true,
          "format": ["--aggressive"]
        },
        {
          "name": "force",
          "exportedName": "Force",
          "type": "boolean",
          "description": "reinstall hooks without checking config version",
          "noValue": true,
          "format": ["--aggressive"]
        },
        {
          "name": "noColors",
          "exportedName": "NoColors",
          "type": "boolean",
          "description": "disable colored output",
          "noValue": true,
          "format": ["--no-colors"]
        },
        {
          "name": "verbose",
          "exportedName": "Verbose",
          "type": "boolean",
          "description": "",
          "noValue": true,
          "format": ["--verbose"]
        }
      ]
    }
  ]
}

=== stephenwilliams/go-clitools/_build/specifications/misspell.json
{
  "$schema": "https://raw.githubusercontent.com/stephenwilliams/go-clitools/main/_build/tool.schema.json",
  "name": "misspell",
  "description": "Correct commonly misspelled English words... quickly.",
  "executableName": "misspell",
  "package": "misspell",
  "exportedName": "Misspell",
  "versionProvider": {
    "commandArgs": ["-v"],
    "selector": {
      "equalsReplace": {
        "old": "dev",
        "new": "0.0.0-dev"
      }
    }
  },
  "groups": [
    {
      "package": "@",
      "description": "",
      "commands": [
        {
          "name": "misspell",
          "exportedName": "Misspell",
          "argumentSets": [
            {
              "name": "@",
              "exportedNameSuffix": "",
              "args": [
                {
                  "name": "files",
                  "type": "stringSlice",
                  "excludeDefaultValue": true
                }
              ]
            }
          ],
          "options": [
            {
              "name": "debug",
              "exportedName": "Debug",
              "description": "Debug matching, very slow",
              "type": "boolean",
              "noValue": true,
              "format": ["-debug"]
            },
            {
              "name": "error",
              "exportedName": "Error",
              "description": "Exit with 2 if misspelling found",
              "type": "boolean",
              "noValue": true,
              "format": ["-error"]
            },
            {
              "name": "format",
              "exportedName": "Format",
              "description": "'csv', 'sqlite3' or custom Golang template for output",
              "type": "string",
              "format": ["-f","%s"],
              "valueJoin": ","
            },
            {
              "name": "ignoredCorrections",
              "exportedName": "IgnoredCorrections",
              "description": "ignore the following corrections",
              "type": "stringSlice",
              "format": ["-f","%s"],
              "valueJoin": ","
            },
            {
              "name": "workers",
              "exportedName": "Workers",
              "description": "Number of workers, 0 = number of CPUs",
              "type": "int",
              "format": ["-j","%v"]
            },
            {
              "name": "locale",
              "exportedName": "Locale",
              "description": "Correct spellings using locale preferences for US or UK.\nDefault is to use a neutral variety of English.\nSetting locale to US will correct the British spelling of 'colour' to 'color'",
              "type": "string",
              "format": ["-locale", "%v"]
            },
            {
              "name": "output",
              "exportedName": "Output",
              "description": "output file or [stderr|stdout|] (default 'stdout')",
              "type": "string",
              "format": ["-o","%s"]
            },
            {
              "name": "source",
              "exportedName": "Source",
              "description": "Source mode: auto=guess, go=golang source, text=plain or markdown-like text (default \"auto\")",
              "type": "string",
              "format": ["-source","%s"]
            },
            {
              "name": "write",
              "exportedName": "Write",
              "description": "Overwrite file with corrections (default is just to display)",
              "type": "boolean",
              "noValue": true,
              "format": ["-w"]
            }
          ]
        }
      ]
    }
  ]
}

=== stephenwilliams/go-clitools/_build/specifications/svu.json
{
  "$schema": "https://raw.githubusercontent.com/stephenwilliams/go-clitools/main/_build/tool.schema.json",
  "name": "Semantic Version Util",
  "description": "Semantic Version Util is a tool to manage semantic versions at ease!",
  "executableName": "svu",
  "package": "svu",
  "exportedName": "SVU",
  "versionProvider": {
    "commandArgs": ["--version"],
    "captureStderr": true,
    "selector": {
      "splitLine": {
        "index": 0
      },
      "splitString": {
        "index": 2
      }
    }
  },
  "downloaders": {
    "githubRelease": {
      "owner": "caarlos0",
      "repository": "svu",
      "tagPrefix": "v",
      "assetSelector": "svu_{{trimPrefix \"v\" .Version}}_{{.OS}}_({{.Arch}}|all).tar.gz",
      "assetSelectorRegexp": true,
      "archived": true,
      "archivePath": "svu"
    }
  },
  "defaultToolProvider": {
    "chain": {
      "providers": [
        {
          "path": true
        },
        {
          "downloader": {
            "downloader": "GithubReleaseDownloader"
          }
        }
      ]
    }
  },
  "groups": [
    {
      "package": "@",
      "description": "",
      "commands": [
        {
          "name": "next",
          "description": "prints the next version based on the git log",
          "exportedName": "Next",
          "subCommandPath": ["next"],
          "optionSets": [
            {
              "name": "base"
            }
          ]
        },
        {
          "name": "major",
          "description": "new major version",
          "exportedName": "Major",
          "subCommandPath": ["major"],
          "optionSets": [
            {
              "name": "base"
            }
          ]
        },
        {
          "name": "minor",
          "description": "new minor version",
          "exportedName": "Minor",
          "subCommandPath": ["minor"],
          "optionSets": [
            {
              "name": "base"
            }
          ]
        },
        {
          "name": "patch",
          "description": "new patch version",
          "exportedName": "Patch",
          "subCommandPath": ["patch"],
          "optionSets": [
            {
              "name": "base"
            }
          ]
        },
        {
          "name": "current",
          "description": "prints current version",
          "exportedName": "Current",
          "subCommandPath": ["current"],
          "optionSets": [
            {
              "name": "base"
            }
          ]
        }
      ]
    }
  ],
  "optionSets": [
    {
      "name": "base",
      "description": "",
      "options": [
        {
          "name": "metadata",
          "exportedName": "Metadata",
          "type": "boolean",
          "description": "discards pre-release and build metadata if set to false",
          "format": ["--metadata", "%t"]
        },
        {
          "name": "preRelease",
          "exportedName": "PreRelease",
          "type": "boolean",
          "description": "discards pre-release metadata if set to false",
          "format": ["--pre-release", "%t"]
        },
        {
          "name": "build",
          "exportedName": "Build",
          "type": "boolean",
          "description": "discards build metadata if set to false",
          "format": ["--build", "%t"]
        },
        {
          "name": "tagMode",
          "exportedName": "TagMode",
          "type": "string",
          "description": "determines if latest tag of the current or all branches will be used",
          "format": ["--tag-mode", "%s"]
        }
      ]
    }
  ]
}

=== stephenwilliams/go-clitools/_build/specifications/goreleaser.json
{
  "$schema": "https://raw.githubusercontent.com/stephenwilliams/go-clitools/main/_build/tool.schema.json",
  "name": "GoReleaser",
  "description": "Deliver Go binaries as fast and easily as possible",
  "executableName": "goreleaser",
  "package": "goreleaser",
  "exportedName": "GoReleaser",
  "versionProvider": {
    "commandArgs": ["--version"],
    "selector": {
      "splitLine": {
        "index": 0
      },
      "splitString": {
        "index": 2
      }
    }
  },
  "groups": [
    {
      "package": "@",
      "description": "",
      "commands": [
        {
          "name": "build",
          "description": "Builds the current project",
          "exportedName": "Build",
          "subCommandPath": ["build"],
          "options": [
            {
              "name": "skipPostHooks",
              "exportedName": "SkipPostHooks",
              "type": "boolean",
              "description": "Skips all post-build hooks",
              "noValue": true,
              "format": ["--skip-post-hooks"]
            },
            {
              "name": "skipValidate",
              "exportedName": "SkipValidate",
              "type": "boolean",
              "description": "Skips several sanity checks",
              "noValue": true,
              "format": ["--skip-validate"]
            }
          ],
          "optionSets": [
            {
              "name": "config"
            },
            {
              "name": "build"
            }
          ]
        },
        {
          "name": "check",
          "description": "Checks if configuration is valid",
          "exportedName": "Check",
          "subCommandPath": ["check"],
          "optionSets": [
            {
              "name": "config"
            }
          ]
        },
        {
          "name": "init",
          "description": "Generates a .goreleaser.yml file",
          "exportedName": "Init",
          "subCommandPath": ["init"],
          "optionSets": [
            {
              "name": "config"
            }
          ]
        },
        {
          "name": "release",
          "description": "",
          "exportedName": "Release",
          "subCommandPath": ["release"],
          "options": [
            {
              "name": "releaseFooter",
              "exportedName": "ReleaseFooter",
              "type": "string",
              "description": "Load custom release notes footer from a markdown file",
              "format": ["--release-footer","%s"]
            },
            {
              "name": "releaseHeader",
              "exportedName": "ReleaseHeader",
              "type": "string",
              "description": "Load custom release notes header from a markdown file",
              "format": ["--release-header","%s"]
            },
            {
              "name": "releaseNotes",
              "exportedName": "ReleaseNotes",
              "type": "string",
              "description": "Load custom release notes from a markdown file",
              "format": ["--release-notes","%s"]
            },
            {
              "name": "skipPublish",
              "exportedName": "SkipPublish",
              "type": "boolean",
              "description": "Skips publishing artifacts",
              "noValue": true,
              "format": ["--skip-publish"]
            },
            {
              "name": "skipSign",
              "exportedName": "SkipSign",
              "type": "boolean",
              "description": "Skips signing the artifacts",
              "noValue": true,
              "format": ["--skip-sign"]
            },
            {
              "name": "skipValidate",
              "exportedName": "SkipValidate",
              "type": "boolean",
              "description": "Skips several sanity checks",
              "noValue": true,
              "format": ["--skip-validate"]
            }
          ],
          "optionSets": [
            {
              "name": "config"
            },
            {
              "name": "build"
            }
          ]
        }
      ]
    }
  ],
  "optionSets": [
    {
      "name": "config",
      "options": [
        {
          "name": "config",
          "exportedName": "Config",
          "type": "string",
          "description": "Load configuration from file",
          "format": ["--config","%s"]
        }
      ]
    },
    {
      "name": "build",
      "options": [
        {
          "name": "parallelism",
          "exportedName": "Parallelism",
          "type": "int",
          "description": "Amount tasks to run concurrently\n\n defaults to the number of logical CPUs usable by the current process",
          "format": ["--parallelism","%d"]
        },
        {
          "name": "removeDist",
          "exportedName": "RemoveDist",
          "type": "boolean",
          "description": "Remove the dist folder before building",
          "noValue": true,
          "format": ["--rm-dist"]
        },
        {
          "name": "snapshot",
          "exportedName": "Snapshot",
          "type": "boolean",
          "description": "Generate an unversioned snapshot build, skipping all validations and without publishing any artifacts",
          "noValue": true,
          "format": ["--snapshot"]
        },
        {
          "name": "timeout",
          "exportedName": "Timeout",
          "type": "duration",
          "description": "Timeout to the entire build process (default 30m0s)",
          "noValue": false,
          "format": ["--timeout","%s"]
        }
      ]
    }
  ]
}
