=== stephenwilliams/go-clitools/_build/tool.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/stephenwilliams/go-clitools/main/_build/tool.schema.json",
  "title": "CLI Tool specification schema",
  "description": "Used to generate CLI tool libraries",
  "definitions": {
    "tool": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string",
          "format": "uri"
        },
        "name": {
          "type": "string",
          "description": "Name of the CLI tool"
        },
        "description": {
          "type": "string",
          "description": "Description of the CLI tool"
        },
        "executableName": {
          "type": "string",
          "description": "Name of the executable"
        },
        "exportedName": {
          "type": "string",
          "description": "The exported name of the tool. Used for naming the tool info"
        },
        "package": {
          "type": "string",
          "pattern": "^([A-z0-9]*)$"
        },
        "groups": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commandGroup"
          },
          "uniqueItems": true,
          "minItems": 1
        },
        "optionSets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/optionSet"
          },
          "uniqueItems": true
        },
        "downloaders": {
          "$ref": "#/definitions/downloaders"
        },
        "defaultToolProvider": {
          "$ref": "#/definitions/toolProvider"
        },
        "versionProvider": {
          "$ref": "#/definitions/versionProvider"
        }
      },
      "required": [
        "name",
        "description",
        "executableName",
        "exportedName",
        "package",
        "groups",
        "versionProvider"
      ]
    },
    "stringReplacer": {
      "type": "object",
      "properties": {
        "old": {
          "type": "string"
        },
        "new": {
          "type": "string"
        },
        "numberOfReplacements": {
          "type": "integer"
        }
      },
      "required": [
        "old",
        "new"
      ]
    },
    "versionSelector": {
      "type": "object",
      "properties": {
        "splitLine": {
          "type": "object",
          "properties": {
            "index": {
              "type": "integer"
            }
          },
          "required": ["index"]
        },
        "splitString": {
          "type": "object",
          "properties": {
            "index": {
              "type": "integer"
            },
            "separator": {
              "type": "string",
              "default": " "
            }
          },
          "required": ["index"]
        },
        "stringReplace": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/stringReplacer"
          }
        },
        "trimPrefix": {
          "type": "string"
        },
        "trimSuffix": {
          "type": "string"
        },
        "equalsReplace": {
          "$ref": "#/definitions/stringReplacer"
        }
      }
    },
    "versionProvider": {
      "type": "object",
      "properties": {
        "commandArgs": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        },
        "captureStderr": {
          "type": "boolean",
          "default": false
        },
        "selector": {
          "$ref": "#/definitions/versionSelector"
        }
      },
      "required": [
        "commandArgs",
        "selector"
      ]
    },
    "goType": {
      "enum": [
        "boolean",
        "duration",
        "int",
        "string",
        "stringSlice"
      ]
    },
    "option": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "exportedName": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/goType"
        },
        "format": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        },
        "valueJoin": {
          "type": "string",
          "description": "When using type '[]string' and this is set, it changes the value injected to be string joined on this character"
        },
        "required": {
          "type": "boolean"
        },
        "noValue": {
          "type": "boolean"
        },
        "repeated": {
          "type": "boolean",
          "description": "Only valid for slice types. Whether or not the format is repeated for each value of the slice."
        },
        "append": {
          "type": "boolean",
          "description": "Only valid for slice types. Appends the values to the args array."
        }
      },
      "required": [
        "name",
        "exportedName",
        "type",
        "format"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "pattern": ".*Slice"
              }
            }
          },
          "then": {
            "oneOf": [
              {
                "required": ["valueJoin"]
              },
              {
                "required": ["repeated"]
              },
              {
                "required": ["append"]
              }
            ]
          }
        }
      ]
    },
    "argumentSet": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "exportedNameSuffix": {
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/argument"
          },
          "uniqueItems": true
        }
      },
      "required": [
        "exportedNameSuffix",
        "args"
      ]
    },
    "argument": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/goType"
        },
        "format": {
          "type": "string"
        },
        "excludeDefaultValue": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "command": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "exportedName": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "subCommandPath": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        },
        "options": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/option"
          },
          "uniqueItems": true
        },
        "optionSets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/optionSetRef"
          }
        },
        "argumentSets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/argumentSet"
          },
          "uniqueItems": true
        },
        "argsFirst": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "exportedName"
      ]
    },
    "commandGroup": {
      "type": "object",
      "properties": {
        "package": {
          "type": "string",
          "pattern": "^(@|[A-z0-9]*)$"
        },
        "description": {
          "type": "string"
        },
        "commands": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/command"
          },
          "uniqueItems": true
        },
        "groups": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commandGroup"
          },
          "uniqueItems": true
        }
      },
      "required": [
        "package",
        "description",
        "commands"
      ]
    },
    "optionSet": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "options": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/option"
          },
          "minItems": 1
        }
      },
      "required": [
        "name",
        "options"
      ]
    },
    "optionSetRef": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": ["name"]
    },
    "downloaders": {
      "type": "object",
      "properties": {
        "githubRelease": {
          "$ref": "#/definitions/githubReleaseDownloader"
        }
      }
    },
    "githubReleaseDownloader": {
      "type": "object",
      "properties": {
        "owner": {
          "type": "string",
          "description": "GitHub repository owner"
        },
        "repository": {
          "type": "string",
          "description": "GitHub repository name"
        },
        "tagPrefix": {
          "type": "string"
        },
        "assetSelector": {
          "type": "string"
        },
        "assetSelectorRegexp": {
          "type": "boolean"
        },
        "archived": {
          "type": "boolean"
        },
        "archivePath": {
          "type": "string"
        },
        "multipleReleases": {
          "type": "boolean",
          "description": "When multiple different \"releases\" are released from a singular GitHub repository"
        },
        "multipleReleasesTagPrefix": {
          "type": "string",
          "description": "When multiple different \"releases\" are released from a singular GitHub repository."
        }
      },
      "required": [
        "owner",
        "repository",
        "assetSelector"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "archived": {
                "const": true
              }
            }
          },
          "then": {
            "properties": {
              "archivePath": {
                "pattern": ".+"
              }
            },
            "required": [
              "archivePath"
            ]
          }
        }
      ]
    },
    "toolProvider": {
      "type": "object",
      "properties": {
        "chain": {
          "type": "object",
          "properties": {
            "providers": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/toolProvider"
              },
              "minItems": 2
            }
          }
        },
        "definedToolPath": {
          "type": "object",
          "properties": {
            "path": {
              "type": "string"
            }
          },
          "required": [
            "path"
          ]
        },
        "downloader": {
          "type": "object",
          "properties": {
            "downloader": {
              "type": "string"
            }
          },
          "required": ["downloader"]
        },
        "path": {
          "type": "boolean"
        }
      },
      "oneOf": [
        {
          "required": ["chain"]
        },
        {
          "required": ["definedToolPath"]
        },
        {
          "required": ["downloader"]
        },
        {
          "required": ["path"]
        }
      ]
    }
  },
  "$ref": "#/definitions/tool"
}

=== stephenwilliams/go-clitools/_build/specifications/kubeconform.json
{
  "$schema": "https://raw.githubusercontent.com/stephenwilliams/go-clitools/main/_build/tool.schema.json",
  "name": "kubeconform",
  "description": "A FAST Kubernetes manifests validator, with support for Custom Resources! ",
  "executableName": "kubeconform",
  "package": "kubeconform",
  "exportedName": "KubeConform",
  "versionProvider":{
    "commandArgs": ["-v"],
    "selector": {
      "splitLine": {
        "index": 0
      }
    }
  },
  "downloaders": {
    "githubRelease": {
      "owner": "yannh",
      "repository": "kubeconform",
      "tagPrefix": "v",
      "assetSelector": "kubeconform-{{.OS}}-{{.Arch}}.tar.gz",
      "archived": true,
      "archivePath": "kubeconform"
    }
  },
  "defaultToolProvider": {
    "chain": {
      "providers": [
        {
          "path": true
        },
        {
          "downloader": {
            "downloader": "GithubReleaseDownloader"
          }
        }
      ]
    }
  },
  "groups": [
    {
      "package": "@",
      "description": "",
      "commands": [
        {
          "name": "kubeconform",
          "exportedName": "KubeConform",
          "argumentSets": [
            {
              "name": "@",
              "exportedNameSuffix": "",
              "args": [
                {
                  "name": "fileOrFolder",
                  "type": "string",
                  "excludeDefaultValue": true
                }
              ]
            },
            {
              "name": "@",
              "exportedNameSuffix": "WithFilesOrFolders",
              "args": [
                {
                  "name": "filesOrFolders",
                  "type": "stringSlice"
                }
              ]
            }
          ],
          "options": [
            {
              "name": "cache",
              "exportedName": "Cache",
              "description": "cache schemas downloaded via HTTP to this folder",
              "type": "string",
              "format": ["-cache", "%s"]
            },
            {
              "name": "cpuProf",
              "exportedName": "CPUProf",
              "description": "debug - log CPU profiling to file",
              "type": "string",
              "format": ["-cpu-prof", "%s"]
            },
            {
              "name": "ignoreFilenamePattern",
              "exportedName": "IgnoreFilenamePattern",
              "description": "regular expression specifying paths to ignore",
              "type": "stringSlice",
              "format": ["-ignore-filename-pattern", "%s"],
              "repeated": true
            },
            {
              "name": "ignoreMissingSchemas",
              "exportedName": "IgnoreMissingSchemas",
              "description": "skip files with missing schemas instead of failing",
              "type": "boolean",
              "noValue": true,
              "format": ["-ignore-missing-schemas"]
            },
            {
              "name": "kubernetesVersion",
              "exportedName": "KubernetesVersion",
              "description": "version of Kubernetes to validate against, e.g.: 1.18.0 (default \"master\")",
              "type": "string",
              "format": ["-kubernetes-version", "%s"]
            },
            {
              "name": "n",
              "exportedName": "N",
              "description": "number of goroutines to run concurrently (default 4)",
              "type": "int",
              "format": ["-n", "%d"]
            },
            {
              "name": "output",
              "exportedName": "Output",
              "description": "output format - json, junit, tap, text (default \"text\")",
              "type": "string",
              "format": ["-output", "%s"]
            },
            {
              "name": "reject",
              "exportedName": "Reject",
              "description": "comma-separated list of kinds to reject",
              "type": "string",
              "format": ["-reject", "%s"]
            },
            {
              "name": "schemaLocation",
              "exportedName": "SchemaLocation",
              "description": "override schemas location search path",
              "type": "stringSlice",
              "format": ["-schema-location","%s"],
              "repeated": true
            },
            {
              "name": "skip",
              "exportedName": "Skip",
              "description": "comma-separated list of kinds to ignore",
              "type": "string",
              "format": ["-skip", "%s"]
            },
            {
              "name": "strict",
              "exportedName": "Strict",
              "description": "disallow additional properties not in schema",
              "type": "boolean",
              "noValue": true,
              "format": ["-strict"]
            },
            {
              "name": "summary",
              "exportedName": "Summary",
              "description": "print a summary at the end (ignored for junit output)",
              "type": "boolean",
              "noValue": true,
              "format": ["-summary"]
            },
            {
              "name": "verbose",
              "exportedName": "Verbose",
              "description": "print results for all resources (ignored for tap and junit output)",
              "type": "boolean",
              "noValue": true,
              "format": ["-verbose"]
            }
          ]
        }
      ]
    }
  ]
}
